#ifndef H_SCALES
#define H_SCALES

#include "../pedal/pedal.h"

namespace Scale {
  const uint8_t NUM_SCALES = 7;

  const uint8_t MODE_IONIAN = 0;
  const uint8_t MODE_DORIAN = 1;
  const uint8_t MODE_PHRYGIAN = 2;
  const uint8_t MODE_LYDIAN = 3;
  const uint8_t MODE_MIXOLYDIAN = 4;
  const uint8_t MODE_AEOLIAN = 5;
  const uint8_t MODE_LOCRIAN = 6;

  const double ionian[8] = {
    POSITION_ROOT,
    POSITION_MAJOR_SECOND,
    POSITION_MAJOR_THIRD,
    POSITION_PERFECT_FOURTH,
    POSITION_PERFECT_FIFTH,
    POSITION_MAJOR_SIXTH,
    POSITION_MAJOR_SEVENTH,
    POSITION_OCTAVE,
  };

  const double dorian[8] = {
    POSITION_ROOT,
    POSITION_MAJOR_SECOND,
    POSITION_MINOR_THIRD,
    POSITION_PERFECT_FOURTH,
    POSITION_PERFECT_FIFTH,
    POSITION_MAJOR_SIXTH,
    POSITION_MINOR_SEVENTH,
    POSITION_OCTAVE,
  };

  const double phrygian[8] = {
    POSITION_ROOT,
    POSITION_MINOR_SECOND,
    POSITION_MINOR_THIRD,
    POSITION_PERFECT_FOURTH,
    POSITION_PERFECT_FIFTH,
    POSITION_MINOR_SIXTH,
    POSITION_MINOR_SEVENTH,
    POSITION_OCTAVE,
  };

  const double lydian[8] = {
    POSITION_ROOT,
    POSITION_MAJOR_SECOND,
    POSITION_MAJOR_THIRD,
    POSITION_TRITONE,
    POSITION_PERFECT_FIFTH,
    POSITION_MAJOR_SIXTH,
    POSITION_MAJOR_SEVENTH,
    POSITION_OCTAVE,
  };

  const double mixolydian[8] = {
    POSITION_ROOT,
    POSITION_MAJOR_SECOND,
    POSITION_MAJOR_THIRD,
    POSITION_PERFECT_FOURTH,
    POSITION_PERFECT_FIFTH,
    POSITION_MAJOR_SIXTH,
    POSITION_MINOR_SEVENTH,
    POSITION_OCTAVE,
  };

  const double aeolian[8] = {
    POSITION_ROOT,
    POSITION_MAJOR_SECOND,
    POSITION_MINOR_THIRD,
    POSITION_PERFECT_FOURTH,
    POSITION_PERFECT_FIFTH,
    POSITION_MINOR_SIXTH,
    POSITION_MINOR_SEVENTH,
    POSITION_OCTAVE,
  };

  const double locrian[8] = {
    POSITION_ROOT,
    POSITION_MINOR_SECOND,
    POSITION_MINOR_THIRD,
    POSITION_PERFECT_FOURTH,
    POSITION_TRITONE,
    POSITION_MINOR_SIXTH,
    POSITION_MINOR_SEVENTH,
    POSITION_OCTAVE,
  };

  const double** getScale();
  double anyNote();
  void run();
  void next();
  void anyScale();
}

#endif